# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        simulat: 3
        sim2real: 3
        robot: 3
        transfer: 2
        reinforcement learning: 1
        industr: 3
        practical: 2
